name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Use npm install because the repository doesn't include a package-lock
      # file yet. This generates one automatically for future runs.
      - run: npm install
      - run: npm run build
      - name: Set up Git user
        run: |
          git config --global user.name "FeroxShark"
          git config --global user.email "Feroxshark@gmail.com"
      - run: npx gh-pages -d dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
